New structure
Kat-ies/Coursework pull request #7
Opened 2021-02-15 15:11 UTC by Kat-ies

2021-02-15 17:23 UTC, Vitonka requested changes

2021-02-15 17:23 UTC, Vitonka commented on src/zips_from_google-drive.py
> +import zipfile
Странное название: либо нижнее подчёркивание везде используйте, либо дефис

2021-02-15 17:23 UTC, Vitonka commented on src/zips_from_google-drive.py
> +directories = ['/content/drive/My Drive/КУ Курсачи/Курсовой проект 2020/WIDER_FACE (zip)/WIDER_train.zip']
Слишком длинная строчка

2021-02-15 17:23 UTC, Vitonka commented on src/zips_from_google-drive.py
> +# function drive_connect connects to google-drive
Если хочется прокомментировать что же делает функция (а желание очень хорошее), лучше использовать docstring, чем простые комменты. Пример тут https://yandex.ru/turbo/pythonist.ru/s/docstrings-dokumentirovanie-koda-v-python/

2021-02-15 17:23 UTC, Vitonka commented on src/zips_from_google-drive.py
> +        z.append(zipfile.ZipFile(zips, 'r'))
Вместо этого можно написать
`
z = [zipfile.ZipFile(zips, 'r') for zips in directories]
`

2021-02-15 17:23 UTC, Vitonka commented on src/zips_from_google-drive.py
> +    for archives in z:
Да или даже если дальше так используется, то зачем нам вообще z, если мы можем сразу итерироваться по directories?

2021-02-15 17:23 UTC, Vitonka commented on src/visualization.py
> +COLS = 5
Так ведь выше уже были COLUMNS

2021-02-15 17:23 UTC, Vitonka commented on src/visualization.py
> +Rectangle = namedtuple('Rectangle', 'x y w h')
В двух файлах дублируется. Надо бы может вынести куда

2021-02-15 17:23 UTC, Vitonka commented on src/new_dataset_creation.py
> +def ds_create(images_dict, frames_dict):
Если ds - это сокращение от dataset, то лучше уж полностью название писать

2021-02-15 17:23 UTC, Vitonka commented on src/images_and_frames.py
> +Rectangle = namedtuple('Rectangle', 'x y w h')
А он даже в трёх повторяется!

2021-02-15 17:25 UTC, Kat-ies commented on src/zips_from_google-drive.py
> +import zipfile
принято :)

2021-02-15 17:32 UTC, Vitonka approved these changes

2021-02-15 19:35 UTC, Kat-ies commented on src/visualization.py
> +COLS = 5
а там было другое значение констаты (была 1, а тут нужна 5). Мы же по идее не должны менять значения констант (на то они и константы), поэтому я сделала ещё одну переменную

2021-02-15 19:38 UTC, Kat-ies commented on src/visualization.py
> +Rectangle = namedtuple('Rectangle', 'x y w h')
хммм... А можно, например, вынести все import-ы, константы (вроде PATH, RANDOM_SEED  и тд), namedtuple и прочее в один общий файл и в остальных файлах уже подключать только его? или так лучше не делать и оставить константы и импорты как есть?

2021-02-15 19:39 UTC, Kat-ies commented on src/new_dataset_creation.py
> +def ds_create(images_dict, frames_dict):
эх, а я надеялась на буквах сэкономить :)

2021-02-15 19:41 UTC, Kat-ies commented on src/images_and_frames.py
> +Rectangle = namedtuple('Rectangle', 'x y w h')
намёк понят:)

2021-02-15 21:41 UTC, Kat-ies commented on src/zips_from_google-drive.py
> +    for archives in z:
сделала)

2021-02-16 09:40 UTC, Vitonka commented on src/visualization.py
> +COLS = 5
Тогда другое название нужно им обеим

2021-02-16 09:42 UTC, Vitonka commented on src/visualization.py
> +Rectangle = namedtuple('Rectangle', 'x y w h')
Импорты обычно так не выносят, а везде импортируют нужные модули.
А вот константы да, в самый раз

2021-02-16 11:24 UTC, merged